# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8542beff8881fb5714ff908cd11bc5c523f2307b8e5d03f57141df1d1c93d1cc856cb9e73206a6f8dbf20ccd904b55691980f1fe4d63f23a5c30ee5ea2619e9

test:
  secret_key_base: 8e2edbc9166251f5573998e1638eca4ba2c98540d481c2a056b4b75a2fe86bfedb3b6fcf3d60314fa592bbcf5ac9487e2a6ad58c64f03c6dbb077b88031b3699

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
